baseURL = "https://masudakoji.github.io/remotelearningprototype/"
languageCode = "ja"
title = "遠隔授業 補助資料"
theme = "hermit"

pygmentsCodefences  = true
pygmentsUseClasses  = true
hasCJKLanguage = true  # If Chinese/Japanese/Korean is your main content language, enable this to make wordCount works right.
rssLimit = 10  # Maximum number of items in the RSS feed.
# copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableEmoji = true  # Shorthand emojis in content files - https://gohugo.io/functions/emojify/


[author]
  name = "Koji Masuda"

[taxonomies]
  tag = "tags"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02"


  themeColor = "#494f5c"

  homeSubtitle = ""

  footerCopyright = ' All rights reserved.'

  justifyContent = true  # Set "text-align: justify" to `.content`.

  relatedPosts = false  # Add a related content section to all single posts page

  code_copy_button = true # Turn on/off the code-copy-button for code-fields

  [[params.social]]
    name = "github"
    url = "https://github.com/masudakoji/remotelearningprototype"

[menu]

#   [[menu.main]]
#     name = "Posts"
#     url = "posts/"
#     weight = 10

  [[menu.main]]
    name = "学生のみなさんへ"
    url = "about-student/"
    weight = 10


  [[menu.main]]
    name = "教員のみなさんへ"
    url = "about-teacher/"
    weight = 20


[markup.goldmark.renderer]
  unsafe = true

